image: Visual Studio 2017
version: 1.4.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
configuration: Release
before_build: nuget restore src\MuonLab.Validation.sln
for:
  - branches:
      only:
        - master
    after_test:
      - dotnet pack src/MuonLab.Validation/MuonLab.Validation.csproj /property:PackageVersion=%APPVEYOR_BUILD_VERSION% /property:Configuration=Release
  - branches:
      except:
        - master
    after_test:
      - dotnet pack src/MuonLab.Validation/MuonLab.Validation.csproj /property:PackageVersion=%APPVEYOR_BUILD_VERSION%-%APPVEYOR_REPO_BRANCH% /property:Configuration=Release
artifacts:
  - path: '**\*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: lYIqcO230Ct+xY1Je+G17ImW6a3ZEHc1uBagpCQWdegbykpkCC3BB4QE0o+mF61/
  on:
    branch:
      - master

